apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: middy
  name: middy
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: middy
  type: LoadBalancer
status:
  loadBalancer: {}
